### ISSUE TITLE
watchman has no --no-pretty option

### ISSUE THREAD

**Issue by koalalorenzo** [sebastianseilund/orca#1]
After linking and installing watchman manually I got this error:

```
ERROR: Unknown option --no-pretty

Watchman:  watchman--no-pretty get-sockname returned with exit code 1 ERROR: Unknown option --no-pretty

events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: watchman--no-pretty get-sockname returned with exit code 1 ERROR: Unknown option --no-pretty

    at ChildProcess.<anonymous> (/Users/lorenzosetale/Repositories/orca/node_modules/sane/node_modules/fb-watchman/index.js:198:18)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:852:16)
    at Socket.<anonymous> (internal/child_process.js:323:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:492:12)
```

What am I doing wrong?

**Comment by sebastianseilund** [comment]
Which watchman version do you have?

**Comment by koalalorenzo** [comment]
I have downloaded the latest available: 0.1.8
(according to npm)

**Comment by sebastianseilund** [comment]
Ah... wrong [watchman](https://www.npmjs.com/package/watchman). You need the [Facebook watchman](https://facebook.github.io/watchman/) project :)

Easy to install with Homebrew: `brew update && brew install watchman`

Verify with:

```
$ watchman -v
4.6.0
```

**Comment by koalalorenzo** [comment]
God! :D 
Can you update the readme with the requirements? that would avoid this problem to the new guys at billy as well ;~)

**Comment by sebastianseilund** [comment]
Done :)
